/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        before: {
            gotoTab: 'checkMinute'
        },

        routes: {
            'tab/:tabId': {
                action: 'gotoTab',
                conditions: {
                    ':tabId': '[a-zA-Z]+'
                }
            }
        },

        refs: {
            main: '>tabpanel'
        },

        control: {
            "main": {
                activeitemchange: 'onTabpanelActiveItemChange'
            }
        }
    },

    onTabpanelActiveItemChange: function(container, value, oldValue, eOpts) {
        this.getApplication().getHistory().add(new Ext.app.Action({
            url: 'tab/' + value.getItemId()
        }), true);
    },

    gotoTab: function(tabId) {
        var tabPanel = this.getMain(), //uses our Controller Reference
        tabCmp = tabPanel.child('#' + tabId);
        tabPanel.setActiveItem(tabCmp || 0);
    },

    checkMinute: function(action) {
        if ((new Date()).getMinutes() % 2) {
            action.resume();
        } else {
            Ext.Msg.alert('Oops,', 'You can only link to this tab during' + 
            ' odd-numbered minutes! Why? Great question.');
        }
    }

});